CREATE DATABASE BBVA_PAGOSERVICIOS
USE BBVA_PAGOSERVICIOS

--
-- Estructura de tabla para la tabla `CLIENTE`
--

CREATE TABLE `CLIENTES`(
`ID_CLIENTE` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
`NOMBRE` VARCHAR(45) NOT NULL,
`DNI` VARCHAR(8) NOT NULL,
`CLAVE` VARCHAR(10) NOT NULL,
`TELEFONO` VARCHAR(9) NOT NULL,
`ESTADO` CHAR(1) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=latin1;


INSERT INTO `CLIENTES`(`ID_CLIENTE`,`NOMBRE`,`DNI`,`TELEFONO`,`ESTADO`) VALUES (1,'AMERICO CORNELIO BALTAZAR','71844254','12345','93573081','A'),
                                                                                (),
                    
CREATE TABLE `TARJETA`(
`IDTARJETA` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
`TIPOTARJETA` VARCHAR(10) NOT NULL,
`NUMEROTARJETA` VARCHAR(16) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `TARJETA`(`IDTARJETA`,`IDTIPOTARJETA`,`NUMEROTARJETA`) VALUES (1,'DEBITO','1234567891234567'),
                                                                          (2,'CREDITO','9876541231234567')
CREATE TABLE `FACTURA`(
`IDCLIENTE` INT NOT NULL,
`IDSERVICIO` INT NOT NULL,
`IDFACTURA` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
`MONTOPAGO` VARCHAR(20) NOT NULL,
`FECHAEMISION` DATE NOT NULL,
`FECHAVECIMIENTO` DATE NOT NULL,
`ESTADOFACTURA` CHAR(1) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `SERVICIO`(
`IDSERVICIO` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
`IDPROVEEDOR` INT NOT NULL,
`TIPOSERVICIO` INT NOT NULL,
`IDENTIFICADOR` VARCHAR(45) NOT NULL,
`ESTADOSERVICIO` CHAR(1)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `TIPOSERVICIO`(
`IDTIPOSERVICIO` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
`DESCRIPCION` VARCHAR(45) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `PROVEEDOR`(
`IDPROVEEDOR` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
`RAZONSOCIAL` VARCHAR(45) NOT NULL,
`IDSERVICIO` INT NOT NULL 
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

``